# 180 Sentinelles - Protocoles de soutien pour aidants

SENTINELLES = [
    # BIENVEILLANCE (1-20)
    {"id": 1, "cat": "bienveillance", "titre": "Prendre soin de soi", "guide": "Accordez-vous 15 minutes par jour pour vous. Vous le méritez."},
    {"id": 2, "cat": "bienveillance", "titre": "Demander de l'aide", "guide": "Appeler un proche, un voisin ou une association. Vous n'etes pas seul."},
    {"id": 3, "cat": "bienveillance", "titre": "Reconnaitre sa fatigue", "guide": "La fatigue n'est pas une faiblesse. C'est un signal d'alarme."},
    {"id": 4, "cat": "bienveillance", "titre": "Accepter ses limites", "guide": "Vous ne pouvez pas tout faire seul. Accepter l'aide est une force."},
    {"id": 5, "cat": "bienveillance", "titre": "Parler de ses emotions", "guide": "Exprimer sa tristesse, sa colere ou sa peur est necessaire pour tenir."},
    {"id": 6, "cat": "bienveillance", "titre": "Le droit a l'erreur", "guide": "Vous n'etes pas parfait. L'erreur est humaine. Pardonnez-vous."},
    {"id": 7, "cat": "bienveillance", "titre": "Faire une pause", "guide": "Sortir prendre l'air, boire un cafe, respirer. Cinq minutes suffisent."},
    {"id": 8, "cat": "bienveillance", "titre": "Dormir", "guide": "Le sommeil est vital. Organisez des relais pour dormir au moins 6 heures."},
    {"id": 9, "cat": "bienveillance", "titre": "Manger equilibre", "guide": "Ne sautez pas de repas. Des plats simples mais nourrissants."},
    {"id": 10, "cat": "bienveillance", "titre": "Faire une activite plaisir", "guide": "Lecture, musique, jardinage. Gardez un moment pour vous chaque jour."},
    {"id": 11, "cat": "bienveillance", "titre": "Ecouter son corps", "guide": "Maux de tete, douleurs dorsales, fatigue intense : reposez-vous."},
    {"id": 12, "cat": "bienveillance", "titre": "Dire non", "guide": "Vous n'etes pas oblige d'accepter toutes les demandes. Apprenez a refuser."},
    {"id": 13, "cat": "bienveillance", "titre": "Consulter un psychologue", "guide": "Parler a un professionnel n'est pas une honte. C'est un acte de courage."},
    {"id": 14, "cat": "bienveillance", "titre": "Joindre un groupe de parole", "guide": "Des aidants comme vous se reunissent pour echanger. Rejoignez-les."},
    {"id": 15, "cat": "bienveillance", "titre": "Ecrire son vécu", "guide": "Tenir un journal peut aider à liberer les emotions."},
    {"id": 16, "cat": "bienveillance", "titre": "Faire du sport doux", "guide": "Marche, yoga, etirements. Bouger aide à evacuer le stress."},
    {"id": 17, "cat": "bienveillance", "titre": "Mediter", "guide": "Quelques minutes de respiration calme. Des applications gratuites existent."},
    {"id": 18, "cat": "bienveillance", "titre": "Rire", "guide": "Regarder une comedie, appeler un ami drole. Le rire est un medicament."},
    {"id": 19, "cat": "bienveillance", "titre": "Feter les petites victoires", "guide": "Le patient a souri ? Vous avez dormi 6 heures ? Celebrez ces moments."},
    {"id": 20, "cat": "bienveillance", "titre": "Se souvenir qui on est", "guide": "Vous n'etes pas qu'un aidant. Vous avez une identite, des reves, des forces."},

    # SOINS QUOTIDIENS (21-40)
    {"id": 21, "cat": "soins", "titre": "Douleur du patient", "guide": "Observer le visage, la respiration. Demander au patient son niveau de douleur de 0 a 10."},
    {"id": 22, "cat": "soins", "titre": "Difficultes respiratoires", "guide": "Installer le patient en position demi-assise. Aerer la piece. Appeler le 15 si aggravation."},
    {"id": 23, "cat": "soins", "titre": "Refus de manger", "guide": "Ne pas forcer. Proposer de petits repas legers. Consulter un medecin si plus de 3 jours."},
    {"id": 24, "cat": "soins", "titre": "Refus de boire", "guide": "Proposer de l'eau par petites gorgees. Glacons ou brumisation. Appeler medecin si signes deshydratation."},
    {"id": 25, "cat": "soins", "titre": "Agitation du patient", "guide": "Parler doucement. Toucher rassurant. Demander un avis medical si persiste."},
    {"id": 26, "cat": "soins", "titre": "Chute du patient", "guide": "Ne pas le relever brusquement. Verifier douleur, conscience. Appeler medecin si besoin."},
    {"id": 27, "cat": "soins", "titre": "Fievre", "guide": "Prendre temperature. Proposer a boire. Paracetamol sur avis medical."},
    {"id": 28, "cat": "soins", "titre": "Constipation", "guide": "Proposer eau, fruits. Masser doucement le ventre. Consulter medecin."},
    {"id": 29, "cat": "soins", "titre": "Nausees", "guide": "Proposer petites gorgees d'eau ou menthe. Aerer la piece."},
    {"id": 30, "cat": "soins", "titre": "Escarres", "guide": "Changer position toutes les 2-3 heures. Surveiller peau. Massages doux."},
    {"id": 31, "cat": "soins", "titre": "Toilette du patient", "guide": "Preserver l'intimite. Etre doux et patient. Expliquer chaque geste."},
    {"id": 32, "cat": "soins", "titre": "Habillage du patient", "guide": "Prevoir vetements amples. Laisser le patient faire ce qu'il peut."},
    {"id": 33, "cat": "soins", "titre": "Sonde urinaire", "guide": "Surveiller fixation. Si douleur ou absence debit, consulter."},
    {"id": 34, "cat": "soins", "titre": "Pansement", "guide": "Lavage des mains. Ne pas toucher la plaie. Suivre les consignes."},
    {"id": 35, "cat": "soins", "titre": "Prevention des chutes", "guide": "Degager les passages. Tapis antiderapant. Lumiere la nuit."},
    {"id": 36, "cat": "soins", "titre": "Mobilisation du patient", "guide": "Mouvements lents, expliques. Utiliser les leviers. Se proteger le dos."},
    {"id": 37, "cat": "soins", "titre": "Soins dentaires", "guide": "Proposer bain de bouche. Brossage doux. Surveiller rougeurs."},
    {"id": 38, "cat": "soins", "titre": "Soins des yeux", "guide": "Nettoyer avec serum physiologique si necessaire."},
    {"id": 39, "cat": "soins", "titre": "Gestion des medicaments", "guide": "Utiliser un pilulier. Verifier dates. Noter les prises."},
    {"id": 40, "cat": "soins", "titre": "Prevention infections", "guide": "Se laver les mains avant et apres chaque soin."},

    # URGENCES (41-60)
    {"id": 41, "cat": "urgences", "titre": "Detresse respiratoire soudaine", "guide": "URGENCE. Appelez le 15. Installez le patient confortablement."},
    {"id": 42, "cat": "urgences", "titre": "Hemmoragie", "guide": "URGENCE. Appelez le 15. Compressez la plaie avec un linge propre."},
    {"id": 43, "cat": "urgences", "titre": "Perte de connaissance", "guide": "URGENCE. Appelez le 15. Mettez en position laterale de securite si possible."},
    {"id": 44, "cat": "urgences", "titre": "Convulsion", "guide": "URGENCE. Protegez la personne, ne mettez rien dans sa bouche. Appelez le 15."},
    {"id": 45, "cat": "urgences", "titre": "Douleur thoracique", "guide": "URGENCE. Appelez le 15. Installez le patient confortablement."},
    {"id": 46, "cat": "urgences", "titre": "Signe d'AVC", "guide": "URGENCE. Visage asymetrique, difficulte parler, faiblesse bras. Appelez le 15."},
    {"id": 47, "cat": "urgences", "titre": "Reaction allergique grave", "guide": "URGENCE. Gonflements, difficulte respirer. Appelez le 15."},
    {"id": 48, "cat": "urgences", "titre": "Hypoglycemie sever", "guide": "URGENCE. Sucre, miel. Si pas amelioration rapide, appelez le 15."},
    {"id": 49, "cat": "urgences", "titre": "Deces du patient", "guide": "URGENCE. Appelez medecin pour constat. Ne restez pas seul, appelez famille."},
    {"id": 50, "cat": "urgences", "titre": "Agitation violente", "guide": "URGENCE. Mettez-vous en securite. Appelez le 15 si danger."},
    {"id": 51, "cat": "urgences", "titre": "Fievre superieure 40°C", "guide": "URGENCE. Appelez medecin. Refraichir le patient sans le couvrir trop."},
    {"id": 52, "cat": "urgences", "titre": "Deshydratation severe", "guide": "URGENCE. Levres seches, peu d'urine, confusion. Appelez medecin."},
    {"id": 53, "cat": "urgences", "titre": "Patient inconsolable", "guide": "URGENCE. Pleurs ou cris sans fin. Appelez equipe soignante."},
    {"id": 54, "cat": "urgences", "titre": "Idees suicidaires patient", "guide": "URGENCE. Ne laissez pas seul. Appelez le 15."},
    {"id": 55, "cat": "urgences", "titre": "Aidant au bord du burn-out", "guide": "URGENCE. Relais immediat. Appelez famille ou ete. 0 800 360 360."},
    {"id": 56, "cat": "urgences", "titre": "Tentative de suicide aidant", "guide": "URGENCE VITALE. Appelez le 15. Ne restez pas seul. Parlez."},
    {"id": 57, "cat": "urgences", "titre": "Maltraitance suspectee", "guide": "URGENCE. Protegez le patient. Appelez 119 (Allo Enfance en danger) si enfant ou personne vulnérable."},
    {"id": 58, "cat": "urgences", "titre": "Incendie dans le logement", "guide": "URGENCE. Evacuez patient. Appelez le 18 (pompiers)."},
    {"id": 59, "cat": "urgences", "titre": "Accident de la route", "guide": "URGENCE. Appelez le 15 et 17 (police). Ne bougez pas les blesses."},
    {"id": 60, "cat": "urgences", "titre": "Catastrophe naturelle", "guide": "URGENCE. Suivez consignes prefecture. Securisez patient. Appelez aide."},
    
    # RELAIS AIDANT (61-80)
    {"id": 61, "cat": "relais", "titre": "Aide professionnelle HAD", "guide": "Contacter l'Hospitalisation à Domicile. Ils coordonnent les soins."},
    {"id": 62, "cat": "relais", "titre": "Garde de répit", "guide": "Une aide à domicile pour quelques heures. Permet de souffler."},
    {"id": 63, "cat": "relais", "titre": "Groupe de parole", "guide": "Échanger avec d'autres aidants. France Alzheimer, France Parkinson."},
    {"id": 64, "cat": "relais", "titre": "Ligne d'écoute", "guide": "0 800 360 360 (gratuit, 24h/24). Des écoutants formés."},
    {"id": 65, "cat": "relais", "titre": "Aide ménagère", "guide": "Quelques heures par semaine. APA ou aide sociale peuvent financer."},
    {"id": 66, "cat": "relais", "titre": "Transport patient", "guide": "Voir avec associations (Croix-Rouge) ou mairie pour transport adapté."},
    {"id": 67, "cat": "relais", "titre": "Aide administrative", "guide": "Assistante sociale de secteur ou CLIC. Elles connaissent les aides."},
    {"id": 68, "cat": "relais", "titre": "Téléassistance", "guide": "Bracelet ou médaillon d'appel d'urgence. Très rassurant."},
    {"id": 69, "cat": "relais", "titre": "Gardiennage", "guide": "Une personne reste quelques heures. Permet d'aller chez le médecin."},
    {"id": 70, "cat": "relais", "titre": "Relais familial", "guide": "Organiser un planning avec frères, soeurs, enfants. Chacun son tour."},
    {"id": 71, "cat": "relais", "titre": "Répit en EHPAD", "guide": "Accueil temporaire 1 à 3 semaines. Se reposer, partir en vacances."},
    {"id": 72, "cat": "relais", "titre": "Plateforme de répit", "guide": "Propose des solutions sur votre secteur. Demandez à la mairie."},
    {"id": 73, "cat": "relais", "titre": "Bénévole accompagnement", "guide": "JALMALV, ASP, Petits Frères des Pauvres. Présence bienveillante."},
    {"id": 74, "cat": "relais", "titre": "APA (Allocation Personnalisée)", "guide": "Aide financière pour payer des aides à domicile. Contacter le département."},
    {"id": 75, "cat": "relais", "titre": "Congé proche aidant", "guide": "66 jours ouvrés de congé (sous conditions). Renseignez-vous."},
    {"id": 76, "cat": "relais", "titre": "Préparation succession", "guide": "Anticiper les démarches auprès d'un notaire. Moins de stress après."},
    {"id": 77, "cat": "relais", "titre": "Groupe Facebook aidants", "guide": "Communautés actives la nuit. Utile quand on ne dort pas."},
    {"id": 78, "cat": "relais", "titre": "Podcast 'Aidants célèbres'", "guide": "Écouter des témoignages quand vous êtes seul dans la voiture."},
    {"id": 79, "cat": "relais", "titre": "Bibliothèque d'emprunt", "guide": "Des livres sur l'aidance existent. Voir la médiathèque locale."},
    {"id": 80, "cat": "relais", "titre": "Bien être", "guide": "Massage, sophrologie, yoga doux. Prenez soin de votre corps."},

    # COMMUNICATION EN FAMILLE (81-100)
    {"id": 81, "cat": "relation", "titre": "Communication non violente", "guide": "\"Je ressens... car j'ai besoin de...\" Évitez les accusations."},
    {"id": 82, "cat": "relation", "titre": "Échanger en famille", "guide": "Réunion hebdomadaire pour répartir les tâches. Sans jugement."},
    {"id": 83, "cat": "relation", "titre": "Exprimer sa fatigue", "guide": "Ne pas cacher son épuisement. \"Je ne peux plus, aidez-moi\"."},
    {"id": 84, "cat": "relation", "titre": "Demander pardon", "guide": "Si vous avez été dur, excusez-vous. Cela apaise les tensions."},
    {"id": 85, "cat": "relation", "titre": "Pardonner", "guide": "Acceptez que vos proches ne fassent pas tout parfaitement."},
    {"id": 86, "cat": "relation", "titre": "Reconnaître ses torts", "guide": "\"J'ai eu tort de crier\". La reconnaissance désamorce."},
    {"id": 87, "cat": "relation", "titre": "Parler de la mort", "guide": "Aborder le sujet avec douceur, sans brutalité, à un moment calme."},
    {"id": 88, "cat": "relation", "titre": "Confier ses peurs", "guide": "Dire \"j'ai peur de ne pas y arriver\" est un soulagement."},
    {"id": 89, "cat": "relation", "titre": "Exprimer sa colère", "guide": "Crier dans un coussin, taper dans un oreiller. Évacuer sans blesser."},
    {"id": 90, "cat": "relation", "titre": "S'affirmer calmement", "guide": "\"Je propose que...\" \"Je pense que...\" Parler posément."},
    {"id": 91, "cat": "relation", "titre": "Négocier", "guide": "Trouver un terrain d'entente plutôt que chercher à vaincre."},
    {"id": 92, "cat": "relation", "titre": "Dire merci", "guide": "Remerciez systématiquement ceux qui aident. Ça motive."},
    {"id": 93, "cat": "relation", "titre": "Féliciter", "guide": "Valorisez les efforts de vos proches. Un petit mot suffit."},
    {"id": 94, "cat": "relation", "titre": "Sourire", "guide": "Un sourire désarme bien des tensions, même intérieures."},
    {"id": 95, "cat": "relation", "titre": "Toucher réconfortant", "guide": "Une main sur l'épaule, une caresse, sans un mot."},
    {"id": 96, "cat": "relation", "titre": "Écoute active", "guide": "Ne pas couper, reformuler, montrer qu'on comprend."},
    {"id": 97, "cat": "relation", "titre": "Mettre des mots", "guide": "\"Je vois que tu es fatigué...\" \"Tu as l'air triste.\""},
    {"id": 98, "cat": "relation", "titre": "Éviter le jugement", "guide": "\"Tu aurais dû...\" ne sert à rien. Dire \"Je comprends ta décision.\""},
    {"id": 99, "cat": "relation", "titre": "Prendre du recul", "guide": "Attendre d'être calme avant de répondre. Sortir 5 minutes."},
    {"id": 100, "cat": "relation", "titre": "Lâcher prise", "guide": "On ne peut pas tout maîtriser. Accepter l'imperfection est une force."},
]

    # FINANCES & AIDES (101-120)
    {"id": 101, "cat": "aide", "titre": "Allocation APA", "guide": "Contacter le département. L'APA aide à financer aides et soins à domicile."},
    {"id": 102, "cat": "aide", "titre": "PCH (Prestation Compensation Handicap)", "guide": "Finance des aides pour personnes handicapées (moins de 60 ans)."},
    {"id": 103, "cat": "aide", "titre": "AJPA (Allocation Journalière Proche Aidant)", "guide": "Si vous arrêtez de travailler pour aider. Jusqu'à 66 jours."},
    {"id": 104, "cat": "aide", "titre": "Complémentaire santé solidaire", "guide": "Aide pour la mutuelle. Contactez votre CPAM."},
    {"id": 105, "cat": "aide", "titre": "Aide aux vacances", "guide": "Secours Populaire, Secours Catholique proposent des départs."},
    {"id": 106, "cat": "aide", "titre": "Chèques énergie", "guide": "Aide pour payer factures d'électricité/gaz. Voir CAF ou CCAS."},
    {"id": 107, "cat": "aide", "titre": "Fonds d'urgence", "guide": "Certaines associations aident en cas de coup dur (factures impayées)."},
    {"id": 108, "cat": "aide", "titre": "Assistante sociale", "guide": "Prenez rendez-vous, elle connaît toutes les aides possibles."},
    {"id": 109, "cat": "aide", "titre": "Caf (Caisse d'Allocations Familiales)", "guide": "Aides au logement, aides familiales. Rapprochez-vous."},
    {"id": 110, "cat": "aide", "titre": "CCAS (Mairie)", "guide": "Centre Communal d'Action Sociale. Ils sont là pour vous."},
    {"id": 111, "cat": "aide", "titre": "ARS (Agence Régionale de Santé)", "guide": "Finance des dispositifs de répit. Voir le site de votre région."},
    {"id": 112, "cat": "aide", "titre": "Mutuelle générale", "guide": "Certaines mutelles ont des services spécifiques aidants."},
    {"id": 113, "cat": "aide", "titre": "Crédit d'impôt", "guide": "Frais d'aide à domicile : crédit d'impôt de 50%. Gardez les factures."},
    {"id": 114, "cat": "aide", "titre": "TVA à 5.5%", "guide": "Pour les prestations d'aide à domicile. Surveillez vos factures."},
    {"id": 115, "cat": "aide", "titre": "Donation", "guide": "Un membre de la famille peut vous faire une donation pour compenser."},
    {"id": 116, "cat": "aide", "titre": "Prêt aidant", "guide": "Certaines banques proposent des prêts à taux zéro pour aidants."},
    {"id": 117, "cat": "aide", "titre": "Épargne salariale", "guide": "Vous pouvez débloquer votre épargne pour raisons familiales (décret)."},
    {"id": 118, "cat": "aide", "titre": "Congé parental", "guide": "Alterner avec congé parental peut aider si un enfant est malade."},
    {"id": 119, "cat": "aide", "titre": "Arrêt maladie", "guide": "En cas d'épuisement, consultez votre médecin. Le burn-out d'aidant existe."},
    {"id": 120, "cat": "aide", "titre": "Invalidité", "guide": "Si le patient devient invalide, certaines aides augmentent."},

    # DEUIL & APRÈS (121-130)
    {"id": 121, "cat": "deuil", "titre": "Le deuil de l'aidant", "guide": "Acceptez votre chagrin. Pleurer est normal et nécessaire."},
    {"id": 122, "cat": "deuil", "titre": "Ne pas rester seul", "guide": "Appelez famille, amis. Ligne d'écoute deuil : 0 800 123 456."},
    {"id": 123, "cat": "deuil", "titre": "Faire le bilan", "guide": "Écrire ce qui a été vécu. Un journal peut aider."},
    {"id": 124, "cat": "deuil", "titre": "Reprendre sa vie", "guide": "Un jour, un pas. Retrouver ses loisirs, ses amis."},
    {"id": 125, "cat": "deuil", "titre": "Sans le patient", "guide": "Parler de lui, regarder des photos. Honorer sa mémoire."},
    {"id": 126, "cat": "deuil", "titre": "Rituel symbolique", "guide": "Planter un arbre, allumer une bougie. Un geste qui apaise."},
    {"id": 127, "cat": "deuil", "titre": "Ne pas culpabiliser", "guide": "Vous avez fait de votre mieux. Cela suffisait."},
    {"id": 128, "cat": "deuil", "titre": "Se reconstruire", "guide": "Prenez le temps. N'écoutez pas ceux qui disent \"passe à autre chose\"."},
    {"id": 129, "cat": "deuil", "titre": "Aider d'autres aidants", "guide": "Votre expérience peut aider. Devenez bénévole d'écoute."},
    {"id": 130, "cat": "deuil", "titre": "Consulter un psychologue", "guide": "Deuil compliqué, dépression. Un pro peut aider."},

    # SOINS PALLIATIFS AVANCÉS (131-145)
    {"id": 131, "cat": "palliatif", "titre": "Sédation profonde", "guide": "Endormissement pour souffrance réfractaire. Décision médicale collégiale."},
    {"id": 132, "cat": "palliatif", "titre": "Arrêt de traitement", "guide": "Discussion avec médecin. Ne jamais arrêter seul un traitement."},
    {"id": 133, "cat": "palliatif", "titre": "Hydratation sous-cutanée", "guide": "Seringue électrique. Surveiller le point de ponction (rougeur, infection)."},
    {"id": 134, "cat": "palliatif", "titre": "Oxygénothérapie", "guide": "Ne pas fumer à proximité. Surveiller les prises électriques."},
    {"id": 135, "cat": "palliatif", "titre": "Douleur osseuse", "guide": "Morphine si prescrite. AINS prudent sous avis médical."},
    {"id": 136, "cat": "palliatif", "titre": "Dysphagie (difficulté avaler)", "guide": "Proposer textures modifiées (mixé, liquide épaissi). Orthophoniste."},
    {"id": 137, "cat": "palliatif", "titre": "Phase agonique", "guide": "Râles, marbrures, extrémités froides. Présence, parole douce."},
    {"id": 138, "cat": "palliatif", "titre": "Constipation opioïdes", "guide": "Laxatifs systématiques préventifs (si morphine). Eau suffisante."},
    {"id": 139, "cat": "palliatif", "titre": "Myoclonies (sursauts)", "guide": "Peut être dû aux opioïdes. Signaler au médecin (rotation possible)."},
    {"id": 140, "cat": "palliatif", "titre": "Délire terminal", "guide": "Halopéridol si prescrit. Parler calmement, ne pas argumenter."},
    {"id": 141, "cat": "palliatif", "titre": "Encombrement bronchique", "guide": "Scopolamine ou atropine en gouttes. Aspiration douce si possible."},
    {"id": 142, "cat": "palliatif", "titre": "OAP terminal", "guide": "Morphine + position assise. Appeler médecin ou 15 rapidement."},
    {"id": 143, "cat": "palliatif", "titre": "Fécalome", "guide": "Toucher rectal systématique si constipation. Extraction douce après antalgie."},
    {"id": 144, "cat": "palliatif", "titre": "Rétention urinaire", "guide": "Globe palpable. Sondage évacuateur. Voir médecin."},
    {"id": 145, "cat": "palliatif", "titre": "Derniers jours", "guide": "Détérioration rapide. Prévenir la famille. Se relayer."},

    # DIRECTIVES ANTICIPÉES (146-150)
    {"id": 146, "cat": "droit", "titre": "Directives anticipées", "guide": "Document écrit qui dit vos volontés. Peut être modifié."},
    {"id": 147, "cat": "droit", "titre": "Personne de confiance", "guide": "Désignée par le patient. Porte-parole et consultation."},
    {"id": 148, "cat": "droit", "titre": "Loi Claeys-Leonetti", "guide": "Interdit l'obstination déraisonnable. Droit à une sédation."},
    {"id": 149, "cat": "droit", "titre": "Tutelle / curatelle", "guide": "Protection juridique si le patient ne peut plus décider."},
    {"id": 150, "cat": "droit", "titre": "Médiation familiale", "guide": "En cas de conflit sur les soins. Un médiateur neutre."},
]
    # PRÉVENTION BURNOUT (151-165)
    {"id": 151, "cat": "prevention", "titre": "Reconnaître l'épuisement", "guide": "Fatigue intense, irritabilité, troubles sommeil. Consultez votre médecin."},
    {"id": 152, "cat": "prevention", "titre": "Score SET (Épuisement)", "guide": "Calculé par Sentylink. Si > 80, alerte la famille. Relais immédiat."},
    {"id": 153, "cat": "prevention", "titre": "Plan de relais", "guide": "Préparez une liste de 3 personnes à contacter en urgence."},
    {"id": 154, "cat": "prevention", "titre": "Roulement famille", "guide": "Chaque membre a son créneau. Appli Partage de planning."},
    {"id": 155, "cat": "prevention", "titre": "Gardiennage nuit", "guide": "Quelqu'un garde le patient la nuit. Vous dormez."},
    {"id": 156, "cat": "prevention", "titre": "Somnolence diurne", "guide": "Signe de fatigue intense. Arrêtez vous, siestez 20 min."},
    {"id": 157, "cat": "prevention", "titre": "Maux de tête persistants", "guide": "Consultez. Parfois signe d'hypertension nerveuse."},
    {"id": 158, "cat": "prevention", "titre": "Perte d'appétit", "guide": "Forcez-vous à manger. Plats faciles (soupe, compote)."},
    {"id": 159, "cat": "prevention", "titre": "Isolement", "guide": "Acceptez l'invitation du voisin. Même une heure."},
    {"id": 160, "cat": "prevention", "titre": "Banir l'alcool", "guide": "L'alcool aggrave l'épuisement. Évitez."},
    {"id": 161, "cat": "prevention", "titre": "Stop au café", "guide": "Le café cache la fatigue. Limitez-vous."},
    {"id": 162, "cat": "prevention", "titre": "Exercice doux", "guide": "Marche 20 min par jour. Endorphines naturelles."},
    {"id": 163, "cat": "prevention", "titre": "Anti-stress", "guide": "Cohérence cardiaque (3x5 min/jour). Apps gratuites."},
    {"id": 164, "cat": "prevention", "titre": "Sophrologie", "guide": "Séances en groupe parfois gratuites (CCAS, hôpital)."},
    {"id": 165, "cat": "prevention", "titre": "Psychiatre", "guide": "Si pensées noires, consulter sans honte."},

    # VIE PRATIQUE (166-175)
    {"id": 166, "cat": "pratique", "titre": "Aménagement du logement", "guide": "Barres d'appui, rampe, lit médicalisé. Ergothérapeute."},
    {"id": 167, "cat": "pratique", "titre": "Lits médicalisés", "guide": "Prescription médecin+ HAD ou pharmacie. Remboursé partiellement."},
    {"id": 168, "cat": "pratique", "titre": "Lève-malade", "guide": "Évite de vous faire mal au dos. Demandez conseil."},
    {"id": 169, "cat": "pratique", "titre": "Fauteuil roulant", "guide": "Mairie peut prêter. Sinon pharmacie, prescriptible."},
    {"id": 170, "cat": "pratique", "titre": "Calendrier partagé", "guide": "Utilisez l'appli Famili-Book de Sentylink ou Google Agenda."},
    {"id": 171, "cat": "pratique", "titre": "Pilulier automatique", "guide": "Oblie-t-il ses médicaments ? Le pilulier sonne."},
    {"id": 172, "cat": "pratique", "titre": "Détecteur chute", "guide": "Patch à porter. Envoie alerte aux proches."},
    {"id": 173, "cat": "pratique", "titre": "Montre GPS", "guide": "Si patient déambule. Localisation et bouton d'urgence."},
    {"id": 174, "cat": "pratique", "titre": "Dossier médical partagé", "guide": "Facilite la coordination entre médecins."},
    {"id": 175, "cat": "pratique", "titre": "Carte aidant", "guide": "Justificatif pour démarches. Demander au département."},

    # RESSOURCES SPIRITUELLES (176-180)
    {"id": 176, "cat": "spirituel", "titre": "Spiritualité quel que soit", "guide": "Croyant ou non, trouver du sens apaise."},
    {"id": 177, "cat": "spirituel", "titre": "Aumônerie", "guide": "Dans hôpitaux. Souvent très doux, pas prosélytes."},
    {"id": 178, "cat": "spirituel", "titre": "Méditation pleine conscience", "guide": "Vivre l'instant sans juger. Apps: Petit Bambou."},
    {"id": 179, "cat": "spirituel", "titre": "Nature", "guide": "Se promener en forêt. Baisser la luminosité, respirer."},
    {"id": 180, "cat": "spirituel", "titre": "Gratitude", "guide": "Chaque soir, noter une petite chose positive du jour."}
]

def get_sentinelles_summary():
    return "\n".join([f"S{s['id']:03d} | {s['titre']} → {s['guide']}" for s in SENTINELLES])
